---
- name: refresh package list
  hosts: all
  tasks:
    - apt: update_cache=yes

- name: configure redis
  hosts: all
  roles:
    - { role: debops.redis, redis_bind: ['0.0.0.0'], redis_sentinel_standalone: False, redis_sentinel_hosts_group: 'redis', redis_hosts_group: 'redis', redis_sentinel_bind: ['0.0.0.0'], redis_server_allow: ['0.0.0.0']  }
